### ISSUE TITLE
Jobs openapi type error 

### ISSUE THREAD

**Issue by richcar58** [tapis-project/tapis-jobs#17]
The Java client breaks on getHistory calls with the following error:

```
Exception in thread "main" edu.utexas.tacc.tapis.client.shared.exceptions.TapisClientException: java.lang.NumberFormatException: For input string: "2022-02-21T19:01:42.199054Z"
	at edu.utexas.tacc.tapis.client.shared.Utils.throwTapisClientException(Utils.java:81)
	at edu.utexas.tacc.tapis.jobs.client.JobsClient.getJobHistory(JobsClient.java:332)
	at edu.utexas.tacc.tapis.cmd.driver.JobGetHistory.main(JobGetHistory.java:46)
```

The Jobs openapi specification getHistory endpoint defines the JobHistoryDisplayDTO type as part of its result.  The created field is defined as a long integer, but the code passes back a string.  

  ```
JobHistoryDisplayDTO
      type: object
      properties:
        event:
          type: string
        created:
          type: integer
          format: int64
        jobStatus:
          type: string
        description:
          type: string
        transferTaskUuid:
          type: string
```

**Comment by scblack321** [comment]
Revisit after Jobs openapi spec is moved to a separate file.

**Comment by zhangwei217245** [comment]
Current `JobHistoryDisplayDTO` definition:
```
JobHistoryDisplayDTO:
      type: object
      properties:
        event:
          type: string
        created:
          type: string
          format: date-time
        eventDetail:
          type: string
        description:
          type: string
        transferTaskUuid:
          type: string
```

**Comment by zhangwei217245** [comment]
Validated on Dev, No longer seems to be an issue. 

The `created` field is now correctly displayed in tapis-cmd and I think our java client works fine on this API now. 

<img width="1946" height="814" alt="Image" src="https://github.com/user-attachments/assets/49f4d76e-d784-45ca-91ea-8a4d721c51fc" />
